name: CI

on:
  push:
    paths: ["**/*.py"]
  pull_request:
    paths: ["**/*.py"]
  workflow_dispatch:

permissions:
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CI実行
        run: |
          echo "CI Executed!"
          exit 0
      - name: ステータス更新 (workflow_dispatch 用)
        if: always() && github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const state = '${{ job.status }}' === 'success' ? 'success' : 'failure';

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: state,
              target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              context: '${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})',
              description: state.charAt(0).toUpperCase() + state.slice(1),
            });
